### ISSUE TITLE
SofTalkのところの合成ボタンを押すと...

### ISSUE THREAD

**Issue by ghost** [ddPn08/aviutil-toys#4]
### SofTalkのところの合成ボタンを押すと...

> "AviUtlToys"を開き、"SofTalk"をクリックする
>適当に入力し、合成を押す 
問題点の`ここをドラッグしてAviUtlに読みいこませて下さい`が表示される

@ddPn08

#Message#
めっちゃ使いやすいソフトですね！字幕設定のやり方も説明していただけるとありがたいです
修正お願いいたします

#Message(2)#
いつも動画見てます！頑張ってください！

**Comment by ddPn08** [comment]
ご報告ありがとうございます！
問題点はドラッグ部分の文字の誤字のことで間違いないでしょうか？
であれば次のリリースまでに修正いたします。

SofTalk機能の使い方は近々使い方を投稿致しますのでもうしばらくお待ち下さい；
いつもありがとうございます！

**Comment by ghost** [comment]
@ddPn08 ありがとうございます！

>問題点はドラッグ部分の文字の誤字のことで間違いないでしょうか？

ドラッグ部分の文字の誤字のこと、間違いないです
