### ISSUE TITLE
SofTalk の AquesTalk 対応中止について

### ISSUE THREAD

**Issue by ghost** [ddPn08/aviutil-toys#5]
### SofTalk の AquesTalk 対応中止について

開発者の **[cncc ゴメス](https://twitter.com/cncc_gomes)** さんがAquesTalk 対応を中止するとツイートしてます
詳しくは https://w.atwiki.jp/softalk/pages/49.html へ
新規に SofTalk をダウンロードする際旧バージョンをダウンロードする必要があります（多分）そのため ReadMeなどに書いておいたほうが
よいと思います

**Comment by ghost** [comment]
一週間たったので再度通知させていただきます
@ddPn08 さん この"Issue"に返信お願いします

**Comment by ddPn08** [comment]
返信遅れました；
こちら現在開発段階ですのでいずれSoftalk最新版にも対応予定です。
その際にwikiも作成するのでそこにSoftalkの仕様について記述しておきます。

**Comment by ghost** [comment]
わかりました
ご対応ありがとうございました
