### ISSUE TITLE
開発遅れます。

### ISSUE THREAD

**Issue by ddPn08** [ddPn08/aviutil-toys#7]
私事ではございますが、受験を控えており開発に時間がかけられないため正式リリースは来年以降になりそうです。

**Comment by ghost** [comment]
受験頑張ってください！
合格しますように...

　合格！
　　 ∧＿∧　　合格！
　　(・∀・)／＼
　　ノ つ つ ● )
　⊂、　ノ　＼／
　　 し′
　　　　合格！
／⌒＼
＼●／∧＿∧　／⌒＼
　∩ (・∀・) ＼●／
　Ｙ￣∥ｙ/∥￣`Φ
　 Lノ/ニニ∥i ソ〉
　　乂/ ノハ ヽ￣
　　`ー-ヽ＿＿|

　合格！
　　 ∧＿∧　　合格！
　　(・∀・)／＼
　　ノ つ つ ● )
　⊂、　ノ　＼／
　　 し′
